spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${port}/${name}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  lifecycle:
    timeout-per-shutdown-phase: 20s

translator:
  papago:
    url: ${url}
    client_id: ${client_id}
    client_secret: ${client_secret}
    params: ${params}

#cloud:
#  aws:
#    s3:
#      bucket: ${bucket}
#    stack:
#      auto: false
#    region:
#      static: ap-northeast-2
#    credentials:
#      access_key: ${access_key}
#      secret_key: ${secret_key}
